### ISSUE TITLE
General instability

### ISSUE THREAD

**Issue by Zekiah-A** [Zekiah-A/WatsonWebsocket#1]
.cs:line 259
   at RplaceServer.SocketServer.StopAsync() in /home/pi/RplaceServer/RplaceServer/SocketServer.cs:line 472
   at ServerInstance.StopAsync() in /home/pi/RplaceServer/RplaceServer/ServerInstance.cs:line 72
   at TKOfficial.Program.<>c.<<Main>b__10_1>d.MoveNext() in /home/pi/RplaceServer/TKOfficial/Program.cs:line 64
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
System.AggregateException: One or more errors occurred. (The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived')
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WatsonWebsocket.WatsonWsServer.DisconnectClient(ClientMetadata client) in /home/pi/RplaceServer/WatsonWebsocketPlus/src/WatsonWebsocket/WatsonWsServer.cs:line 259
   at RplaceServer.SocketServer.StopAsync() in /home/pi/RplaceServer/RplaceServer/SocketServer.cs:line 472
   at ServerInstance.StopAsync() in /home/pi/RplaceServer/RplaceServer/ServerInstance.cs:line 72
   at TKOfficial.Program.<>c.<<Main>b__10_1>d.MoveNext() in /home/pi/RplaceServer/TKOfficial/Program.cs:line 64
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   
   Such errors should not be occuring on a production server.

**Comment by Zekiah-A** [comment]
System.AggregateException: One or more errors occurred. (The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived')                                                                     
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'                                                                  
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)                                                                         
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WatsonWebsocket.WatsonWsServer.DisconnectClient(ClientMetadata client) in /home/pi/RplaceServer/WatsonWebsocketPlus/src/WatsonWebsocket/WatsonWsServer.cs:line 259                                                                   
   at RplaceServer.SocketServer.StopAsync() in /home/pi/RplaceServer/RplaceServer/SocketServer.cs:line 472
   at ServerInstance.StopAsync() in /home/pi/RplaceServer/RplaceServer/ServerInstance.cs:line 72
   at TKOfficial.Program.<>c.<<Main>b__10_1>d.MoveNext() in /home/pi/RplaceServer/TKOfficial/Program.cs:line 64
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()System.AggregateException: One or more errors occurred. (The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived')
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'                                                                  
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)                                                                         
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WatsonWebsocket.WatsonWsServer.DisconnectClient(ClientMetadata client) in /home/pi/RplaceServer/WatsonWebsocketPlus/src/WatsonWebsocket/WatsonWsServer.cs:line 259                                                                   
   at RplaceServer.SocketServer.StopAsync() in /home/pi/RplaceServer/RplaceServer/SocketServer.cs:line 472
   at ServerInstance.StopAsync() in /home/pi/RplaceServer/RplaceServer/ServerInstance.cs:line 72
   at TKOfficial.Program.<>c.<<Main>b__10_1>d.MoveNext() in /home/pi/RplaceServer/TKOfficial/Program.cs:line 64
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
System.AggregateException: One or more errors occurred. (The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived')                                                                     
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'                                                                  
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)                                                                         
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WatsonWebsocket.WatsonWsServer.DisconnectClient(ClientMetadata client) in /home/pi/RplaceServer/WatsonWebsocketPlus/src/WatsonWebsocket/WatsonWsServer.cs:line 259                                                                   
   at RplaceServer.SocketServer.StopAsync() in /home/pi/RplaceServer/RplaceServer/SocketServer.cs:line 472
   at ServerInstance.StopAsync() in /home/pi/RplaceServer/RplaceServer/ServerInstance.cs:line 72
   at TKOfficial.Program.<>c.<<Main>b__10_1>d.MoveNext() in /home/pi/RplaceServer/TKOfficial/Program.cs:line 64
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
